# Aula 4 - Exercícios - Pandas, Fontes de dados e Agregação
### Consulta a internet (Google, Stackoverflow e etc) liberada!!

In [1]:
# Importe as bibliotecas pandas, numpy, glob e sqlalchemy
import pandas as pd
import numpy as np
import sqlalchemy as sqla

### 4.6 Escreva uma função para retornar os registros dos 10 maiores PIBs percapita do brasil (de 2017) a partir do dataframe do exercício anterior. 
#### Escreva uma função genérica que receba como parâmetro um dataframe e o nome da coluna de ordenação.

In [2]:
# Dica 1: Use o método sort_values para ordenar o dataframe. Para uma ordenação descendente use ascending=False.
# Dica 2: Use o atributo iloc para retornar todas as colunas dos 10 primeiros registros.
def top10(df, col):
    """retorne os top 10 registros do dataframe df ordenados por col
    """
    return df.sort_values(by=col, ascending=False).head(10)

In [3]:
# Importar e carregar as funcoes dos exercicios 4 e 5
%run ../Aula4_Ex04/Aula4_Ex04.ipynb
%run ../Aula4_Ex05/Aula4_Ex05.ipynb

In [4]:
## Faça seus testes aqui
df_pib_pop = merge_pop_pib(path_pop, path_pib)
pib_percapita_2017 = pib_percapita(df_pib_pop)

top10(pib_percapita_2017, 'pib_percapita')

,uf,cod_uf,cod_munic,municipio_x,pop2017,cod_ibge7,nivel,municipio_y,2007,2009,2011,2013,2015,2017,pib_percapita
3677,SP,35,36505,Paulínia,102499,3536505,MU,Paulínia (SP),10165558,12607666,9804973,10984788,25492565,35346490,344.847169
5068,RS,43,22004,Triunfo,28289,4322004,MU,Triunfo (RS),5228138,4657360,5232776,5877459,7479634,8803874,311.211920
3575,SP,35,27306,Louveira,45922,3527306,MU,Louveira (SP),3758913,4197033,7033503,9098688,11938395,13805962,300.639389
3155,ES,32,04302,Presidente Kennedy,11742,3204302,MU,Presidente Kennedy (ES),1117822,1558109,6462129,7984035,5803123,3433327,292.397121
2965,MG,31,61908,São Gonçalo do Rio Abaixo,10773,3161908,MU,São Gonçalo do Rio Abaixo (MG),338603,391874,2951330,3532063,1793478,3123367,289.925462
5174,MS,50,07802,Selvíria,6482,5007802,MU,Selvíria (MS),616070,948854,1341239,1668012,1590244,1757236,271.094724
2183,BA,29,29206,São Francisco do Conde,40220,2929206,MU,São Francisco do Conde (BA),3268830,5263313,2490975,1282181,8643550,10211680,253.895574
2523,MG,31,25101,Extrema,34344,3125101,MU,Extrema (MG),1102356,1400501,2387095,4083946,5086205,7529547,219.239081
293,PA,15,08357,Vitória do Xingu,14719,1508357,MU,Vitória do Xingu (PA),54357,69652,111884,373869,805867,3088045,209.799918
3547,SP,35,24709,Jaguariúna,54204,3524709,MU,Jaguariúna (SP),2767079,3353476,4290063,5784633,8891753,11346028,209.320862

In [5]:
# Validação para nota
# Importar e carregar as funcoes dos exercicios 4 e 5
%run ../Aula4_Ex04/Aula4_Ex04.ipynb
%run ../Aula4_Ex05/Aula4_Ex05.ipynb
df_pib_pop = merge_pop_pib(path_pop, path_pib)
pib_percapita_2017 = pib_percapita(df_pib_pop)

test_data = {'cod_ibge7': {3677: '3536505', 3547: '3524709'},
             'municipio_x': {3677: 'Paulínia', 3547: 'Jaguariúna'},
             'uf': {3677: 'SP', 3547: 'SP'},
             'pib_percapita': {3677: 344.8, 3547: 209.3}}
test_data_y = {'cod_ibge7': {3677: '3536505', 3547: '3524709'},
             'municipio_y': {3677: 'Paulínia', 3547: 'Jaguariúna'},
             'uf': {3677: 'SP', 3547: 'SP'},
             'pib_percapita': {3677: 344.8, 3547: 209.3}}
cidades_0_9 = top10(pib_percapita_2017, 'pib_percapita')[['cod_ibge7', 'municipio_x', 'uf', 'pib_percapita']].iloc[[0,9]]
cidades_0_9_y = top10(pib_percapita_2017, 'pib_percapita')[['cod_ibge7', 'municipio_y', 'uf', 'pib_percapita']].iloc[[0,9]]

cidades_0_9['pib_percapita'] = cidades_0_9['pib_percapita'].apply(lambda x: round(x, 1))
cidades_0_9_y['pib_percapita'] = cidades_0_9_y['pib_percapita'].apply(lambda x: round(x, 1))

assert cidades_0_9.to_dict() == test_data or cidades_0_9_y.to_dict() == test_data_y